---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%.
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Dave Gandy
  homepage: http://fortawesome.github.com/Font-Awesome/
  email: dave@davegandy.com
  twitter: https://twitter.com/fontawesome/
  github: https://github.com/FortAwesome/Font-Awesome
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "6.6.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fa6regular

  fullname: Font Awesome 6 Free - regular
  familyname: Font Awesome 6 Free

  copyright: Copyright (C) 2024 Fonticons, Inc.

  ascent: 850
  descent: 150
  weight: "Regular"
glyphs:
  - css: "folder-closed"
    code: 0xE185
    uid: 0ce31eec7654f850bde86508e593426b
    search: []
  - css: heart
    code: 0xF08A
    uid: 37436fdee659f6df5946485325c672db
    search: []
  - css: star
    code: 0xF006
    uid: ea791410dd3647af718f153f13d703f2
    search: []
  - css: user
    code: 0xF007
    uid: 9aa88aeef5ea773d355147fbda7700b3
    search: []
  - css: clock
    code: 0xF017
    uid: d1f2ce1307942338cb61a78714ecf1cc
    search: []
  - css: "rectangle-list"
    code: 0xF022
    uid: 15ed1aeca95e31e923904fc20ce62f7e
    search: []
  - css: flag
    code: 0xF024
    uid: 601bd8b115cd06999f490f865d040561
    search: []
  - css: bookmark
    code: 0xF097
    uid: 5626ec7e8a78259663ea5ee09cdfb884
    search: []
  - css: image
    code: 0xF03E
    uid: 9530158c3c5d59632eded683dbfdf6aa
    search: []
  - css: "pen-to-square"
    code: 0xF044
    uid: 6c10dd5cdc8c49844a40aa7274efe3ea
    search: []
  - css: "circle-xmark"
    code: 0xF05C
    uid: 20f9820962e5a84fa42d0fdad8e8fd11
    search: []
  - css: "circle-check"
    code: 0xF05D
    uid: 08e3fba84560e4e6b53499bd607738d8
    search: []
  - css: "circle-question"
    code: 0xF29C
    uid: b12f51f3164c0fd56d15e6ef5afc5068
    search: []
  - css: eye
    code: 0xF06E
    uid: e1555319065f106b36b81f841a00ef50
    search: []
  - css: "eye-slash"
    code: 0xF070
    uid: 04639e71047b0617b908d003091debde
    search: []
  - css: "calendar-days"
    code: 0xF073
    uid: d4f8ed6edab2d07cf5e6d68f2d078bc4
    search: []
  - css: comment
    code: 0xF0E5
    uid: 8f0bd327c8b9f4ac05ef55c3f95e9a54
    search: []
  - css: folder
    code: 0xF114
    uid: a2f88e6075b2bbde5fb44634c4c24dc0
    search: []
  - css: "folder-open"
    code: 0xF115
    uid: c3f23d22bb39dce87431d96b09b6ea7e
    search: []
  - css: "chart-bar"
    code: 0xF080
    uid: cebfbf981ba12658f0227dc734c7f3c6
    search: []
  - css: comments
    code: 0xF0E6
    uid: f83f1a898013c89abeee9dd6bced36d6
    search: []
  - css: "star-half"
    code: 0xF123
    uid: 42d893f901465e055ccf85c8d8e53e8d
    search: []
  - css: lemon
    code: 0xF094
    uid: d0a726af5d9ff6791163cf27a03c320a
    search: []
  - css: "credit-card"
    code: 0xF283
    uid: a28b45b45fce2277128570194bc2cfeb
    search: []
  - css: "hard-drive"
    code: 0xF0A0
    uid: 87ddb86e67c17c5b4d4af710bb6c075d
    search: []
  - css: "hand-point-right"
    code: 0xF0A4
    uid: a8b779498be9ba04ca5adc65c0f561b0
    search: []
  - css: "hand-point-left"
    code: 0xF0A5
    uid: c2ec7ad85634eeb616f7546077ae73dd
    search: []
  - css: "hand-point-up"
    code: 0xF0A6
    uid: fbf4c402db075e1d0dd600cdc6f82ec8
    search: []
  - css: "hand-point-down"
    code: 0xF0A7
    uid: 6e340ee8da081ab7094928d4bf4aed6f
    search: []
  - css: copy
    code: 0xF0C5
    uid: ef52a0e35d15b45a88dfcfca095ca506
    search: []
  - css: "floppy-disk"
    code: 0xF0C7
    uid: 93f97a8e9045dc804211dab924c3f1e9
    search: []
  - css: square
    code: 0xF0C8
    uid: 4a03cf85f221447ba3ebd07098f9e4e5
    search: []
  - css: envelope
    code: 0xF0E0
    uid: b8c04b4d79d643f8c8bac33c61f9df9f
    search: []
  - css: paste
    code: 0xF0EA
    uid: 206035edd6505458f64d073930af4ff5
    search: []
  - css: lightbulb
    code: 0xF0EB
    uid: 0ed916a74092070093ed239e47bf18f7
    search: []
  - css: bell
    code: 0xF0F3
    uid: 69ff83032dbd74cf28cf2a2dadd5217f
    search: []
  - css: hospital
    code: 0xF47D
    uid: dbe9738d5acd717fc496ebc307790478
    search: []
  - css: "square-plus"
    code: 0xF196
    uid: 81d8f97f55f6422244f2c976f6bb09a3
    search: []
  - css: circle
    code: 0xF1DB
    uid: b06c3ab5c37523929fe2e9236eb985f5
    search: []
  - css: "face-smile"
    code: 0xF118
    uid: 0225237a65185e82049f6cf4af0c0a5f
    search: []
  - css: "face-frown"
    code: 0xF119
    uid: bfbb31664812e3bcc34c10afc1cc8f7f
    search: []
  - css: "face-meh"
    code: 0xF11A
    uid: f6bd93dc100984866d819f682be7bd31
    search: []
  - css: keyboard
    code: 0xF11C
    uid: 728cdd9d81c758640ebebdb0e0983681
    search: []
  - css: calendar
    code: 0xF133
    uid: c38e57cb55653f6a47cad09a1cb77369
    search: []
  - css: "circle-play"
    code: 0xF144
    uid: 5bebe8fcb2cfaf678d5c5492873b352e
    search: []
  - css: "square-minus"
    code: 0xF147
    uid: d6d793eb24e5b2e7d68a09cc2de98041
    search: []
  - css: "square-check"
    code: 0xF14A
    uid: 55060bd11368a58cfeeaf58056505f27
    search: []
  - css: "share-from-square"
    code: 0xF14D
    uid: 2a71b48b5db2065831b6f73c1bb344db
    search: []
  - css: compass
    code: 0xF14E
    uid: 99cabfa10d91a1c95bf725a3b8d807a3
    search: []
  - css: "square-caret-down"
    code: 0xF150
    uid: f76b7f292ce57edd88c1fefe2cc06807
    search: []
  - css: "square-caret-up"
    code: 0xF151
    uid: 8d0e3f910067da7545189998acb02b61
    search: []
  - css: "square-caret-right"
    code: 0xF152
    uid: 83d4a8bf54ce75597bc4104e87d06b98
    search: []
  - css: file
    code: 0xF15B
    uid: d5f1ee9046bac2ef604a72c468d7f505
    search: []
  - css: "file-lines"
    code: 0xF15C
    uid: dd2edc43b657e2f7c7e38a5ae2f64a90
    search: []
  - css: "thumbs-up"
    code: 0xF164
    uid: ac3532ba7efdc0fe2f3f093147f65532
    search: []
  - css: "thumbs-down"
    code: 0xF165
    uid: 297e2bc2dec4e59bbb1ef80ec3e8738a
    search: []
  - css: sun
    code: 0xF185
    uid: f3c4ae84a264ada0051e152085768ba7
    search: []
  - css: moon
    code: 0xF186
    uid: fbf8b5270eda552d2d8312b0a46b5e8c
    search: []
  - css: "square-caret-left"
    code: 0xF191
    uid: f50566adba771b913d3ae2fc93c889a6
    search: []
  - css: "circle-dot"
    code: 0xF192
    uid: fd41fbb7c73182f66c552d75e12b9224
    search: []
  - css: building
    code: 0xF1AD
    uid: 8d142e7beccebbcec6ffdd43c6424599
    search: []
  - css: "file-pdf"
    code: 0xF1C1
    uid: 0ab289367e8da32256833b4bd523e33f
    search: []
  - css: "file-word"
    code: 0xF1C2
    uid: 059c8a52dea8e1d2724ceafa0d02d629
    search: []
  - css: "file-excel"
    code: 0xF1C3
    uid: 9055cadb8f6ef00a25b09fd8cfb975a5
    search: []
  - css: "file-powerpoint"
    code: 0xF1C4
    uid: f0377d43b1a637d82b0aa627780ecd11
    search: []
  - css: "file-image"
    code: 0xF1C5
    uid: 03be30f2b4f353ec646c680969401cc4
    search: []
  - css: "file-zipper"
    code: 0xF1C6
    uid: 318c6f1e1a178fae725cd5688c2b4ebf
    search: []
  - css: "file-audio"
    code: 0xF1C7
    uid: b6442e0790006900c46a8cd7495c9708
    search: []
  - css: "file-video"
    code: 0xF1C8
    uid: 78f8e40dc5ad7fd45543905724d6527b
    search: []
  - css: "file-code"
    code: 0xF1C9
    uid: bcf158ffab9f324de82cdb0904bc24e8
    search: []
  - css: "life-ring"
    code: 0xF1CD
    uid: 083441664be1361edbb408f48ef833cc
    search: []
  - css: "paper-plane"
    code: 0xF1D9
    uid: 8037da95e8e9b2e4e6f81aeace7c1279
    search: []
  - css: futbol
    code: 0xF1E3
    uid: e2fc9ca572f6194378cdd719dc24caad
    search: []
  - css: newspaper
    code: 0xF1EA
    uid: e74bc79e9383e36fb0d50ebf0e078f0a
    search: []
  - css: "bell-slash"
    code: 0xF1F7
    uid: b353948caa3722927aeed9260d50aebf
    search: []
  - css: copyright
    code: 0xF1F9
    uid: 4e594ed456495c3099b33ddf2d6dbada
    search: []
  - css: "closed-captioning"
    code: 0xF20A
    uid: 35e989188b386e2127081d89a430607a
    search: []
  - css: "object-group"
    code: 0xF247
    uid: 89c43a0a2fb644769d0a80f0da928fac
    search: []
  - css: "object-ungroup"
    code: 0xF248
    uid: 508d37cff8b302195514cfe36ff0306e
    search: []
  - css: "note-sticky"
    code: 0xF24A
    uid: b8d65de22e4ffae20e3e61706b7a99b8
    search: []
  - css: clone
    code: 0xF24D
    uid: 8b07817567d11a3532c3b712594319e6
    search: []
  - css: "hourglass-half"
    code: 0xF252
    uid: 920cfa31fa2f4aedd47161ea6b12eb38
    search: []
  - css: hourglass
    code: 0xF254
    uid: 3f226ea821bc8802bbe9a74589a66ce1
    search: []
  - css: "hand-back-fist"
    code: 0xF255
    uid: 33b5fc6e6be19a2621908e1c08a87214
    search: []
  - css: hand
    code: 0xF256
    uid: 4c0aac9a0d326c446038fd08cfe18ac8
    search: []
  - css: "hand-scissors"
    code: 0xF257
    uid: d78d2ac93ffe97fe116e22f5048db64d
    search: []
  - css: "hand-lizard"
    code: 0xF258
    uid: 706d09b18caf3f89cc5e3bed4e580400
    search: []
  - css: "hand-spock"
    code: 0xF259
    uid: 258dadfe28c44b9df32d5df55843be0b
    search: []
  - css: "hand-pointer"
    code: 0xF25A
    uid: 464f55cff215114d9d6a483408228fb5
    search: []
  - css: "hand-peace"
    code: 0xF25B
    uid: cf49b29d8ec696973ce2c2c7274ed039
    search: []
  - css: registered
    code: 0xF25D
    uid: 4b040d18aff0b922bc5da22cc661178c
    search: []
  - css: "calendar-plus"
    code: 0xF271
    uid: bb955e7d1406e1f19a3cfe67b203332e
    search: []
  - css: "calendar-minus"
    code: 0xF272
    uid: 061d47f293c76cfc7e11dd4db5c69d2d
    search: []
  - css: "calendar-xmark"
    code: 0xF273
    uid: 5acbb495111e95478bc46c12ade3e03b
    search: []
  - css: "calendar-check"
    code: 0xF274
    uid: a84b67008b17e3947b83cd46dd0cd483
    search: []
  - css: map
    code: 0xF279
    uid: 186b84fcb71316139645d90ab2b7b01d
    search: []
  - css: message
    code: 0xF27A
    uid: 71f88aaf238fa440341ac684b1bd68f9
    search: []
  - css: "circle-pause"
    code: 0xF28C
    uid: a2c96874b2cd9b6b6516abb208d0549e
    search: []
  - css: "circle-stop"
    code: 0xF28E
    uid: 20323fa9a848d18100352a1bdaf20013
    search: []
  - css: "font-awesome"
    code: 0xF4E6
    uid: 1240b6888d931fc2c8774eb6dce91552
    search: []
  - css: handshake
    code: 0xF2B5
    uid: 5115540a167d46a6f70bb6e748749036
    search: []
  - css: "envelope-open"
    code: 0xF2B7
    uid: f6af55082e5dd760d2c2ee3daf2a17cc
    search: []
  - css: "address-book"
    code: 0xF2BA
    uid: 439f8ad515236334c84231776182be18
    search: []
  - css: "address-card"
    code: 0xF2BC
    uid: f7e4d51e4457108480902323dd27248c
    search: []
  - css: "circle-user"
    code: 0xF2BE
    uid: 94f868757029ac7018019effc63c4d42
    search: []
  - css: "id-badge"
    code: 0xF2C1
    uid: 83f0e07d2fe51e7b05e5732277c0c208
    search: []
  - css: "id-card"
    code: 0xF2C3
    uid: 2fc23cd51c2250422e69f783df80fd4f
    search: []
  - css: "window-maximize"
    code: 0xF2D0
    uid: 1195fd3f3c8d919878e79c9fec32106c
    search: []
  - css: "window-minimize"
    code: 0xF2D1
    uid: 9a096c9423a5aead523bfa94e4fe2a89
    search: []
  - css: "window-restore"
    code: 0xF2D2
    uid: 103c17a65f09022b020a91459e5aaa42
    search: []
  - css: snowflake
    code: 0xF2DC
    uid: e9e887aadb20e85f878fe0eaf9c81369
    search: []
  - css: "trash-can"
    code: 0xF2ED
    uid: 5609225d3ae8e5a6cee2e68e555e576a
    search: []
  - css: images
    code: 0xF302
    uid: 6160cea813d5473e5c332a78a488b4a9
    search: []
  - css: clipboard
    code: 0xF328
    uid: a8a83348ae263f8bedd0de5d8dd21963
    search: []
  - css: "circle-down"
    code: 0xF358
    uid: f3aa00d128ba010fa6266774eee25ba8
    search: []
  - css: "circle-left"
    code: 0xF190
    uid: a1eaa4f79ba397e19ae10ba444ce4608
    search: []
  - css: "circle-right"
    code: 0xF18E
    uid: 0a1e643104df606374bb4d8e00001d97
    search: []
  - css: "circle-up"
    code: 0xF01B
    uid: 95b19a9d35e9eff6b6e61296603df1ef
    search: []
  - css: gem
    code: 0xF3A5
    uid: 963d5ee51e37985a0fb2771222eaca5b
    search: []
  - css: "money-bill-1"
    code: 0xF3D1
    uid: fbcee87368dc4e47d023c2a088f8a2b2
    search: []
  - css: "rectangle-xmark"
    code: 0xF410
    uid: cf8570b7b07754a5d9b83c6c84f31cbc
    search: []
  - css: "chess-bishop"
    code: 0xF43A
    uid: d1dac99830b418937c11e7ac693b72c6
    search: []
  - css: "chess-king"
    code: 0xF43F
    uid: fc9fd88b4a5f6cf844287ec3464e36f9
    search: []
  - css: "chess-knight"
    code: 0xF441
    uid: 445e2ca64698801899d504be9e4b7bdf
    search: []
  - css: "chess-pawn"
    code: 0xF443
    uid: 356c1ac7a03ed5d29eda15513fce73ea
    search: []
  - css: "chess-queen"
    code: 0xF445
    uid: 41c4cb82d0cad572e5e1f9c903874654
    search: []
  - css: "chess-rook"
    code: 0xF447
    uid: 587e537f1f8dd0a8cda51b411a2b5678
    search: []
  - css: "square-full"
    code: 0xF45C
    uid: dfc1bb86ad52c7505478e2d854da98d3
    search: []
  - css: "comment-dots"
    code: 0xF4AD
    uid: e81f13da37ea219c80edd5ee540b3cbe
    search: []
  - css: "face-smile-wink"
    code: 0xF4DA
    uid: 2ea572e54177d838d42ccdfa063279aa
    search: []
  - css: "face-angry"
    code: 0xF556
    uid: f0c4bd1760c6bd1f9958bdd4ca98646f
    search: []
  - css: "face-dizzy"
    code: 0xF567
    uid: 9b9f4502dac8649ab56bb133a18065aa
    search: []
  - css: "face-flushed"
    code: 0xF579
    uid: 1e3c00cc65a6606fb63a99eba05f6c4c
    search: []
  - css: "face-frown-open"
    code: 0xF57A
    uid: 9acd7a057f2f2a72882ab1af417ff235
    search: []
  - css: "face-grimace"
    code: 0xF57F
    uid: c9782c94669eb7f8f29e7ad76f4fc06e
    search: []
  - css: "face-grin"
    code: 0xF580
    uid: c5bfa6487f77f4305ca657190d8a2fb6
    search: []
  - css: "face-grin-wide"
    code: 0xF581
    uid: b7eb3f099491dd366b1d944ba900c25b
    search: []
  - css: "face-grin-beam"
    code: 0xF582
    uid: dbd312a728c802cf74b0d57a08495e92
    search: []
  - css: "face-grin-beam-sweat"
    code: 0xF583
    uid: 6ded9198407a69921f1717a613f643bb
    search: []
  - css: "face-grin-hearts"
    code: 0xF584
    uid: 80883b068ed931ec14cc65c8c16ab514
    search: []
  - css: "face-grin-squint"
    code: 0xF585
    uid: d655d6dc8b468515f8d16fa2102004a5
    search: []
  - css: "face-grin-squint-tears"
    code: 0xF586
    uid: 257d2381ea1b0615bab10e4987c4c0a1
    search: []
  - css: "face-grin-stars"
    code: 0xF587
    uid: 9b1206596606b945bc1c7b0d87370936
    search: []
  - css: "face-grin-tears"
    code: 0xF588
    uid: 632861db8f447e926fd10b655a9bb1ff
    search: []
  - css: "face-grin-tongue"
    code: 0xF589
    uid: bbf6ef24e7ec7d319d755fefeb0d3548
    search: []
  - css: "face-grin-tongue-squint"
    code: 0xF58A
    uid: 2f86e51e366166af8adcfc7642b18cf9
    search: []
  - css: "face-grin-tongue-wink"
    code: 0xF58B
    uid: 550bb97c0baee22313c9edc55121fd67
    search: []
  - css: "face-grin-wink"
    code: 0xF58C
    uid: 23114264fbf3c193e205928cbf3a3d73
    search: []
  - css: "face-kiss"
    code: 0xF596
    uid: 05b0c47b9644f0302e29e08f55f79615
    search: []
  - css: "face-kiss-beam"
    code: 0xF597
    uid: 6dd0037e01a1660a5e29150446895870
    search: []
  - css: "face-kiss-wink-heart"
    code: 0xF598
    uid: 84d3af6d26af808e3dc274cbbce55096
    search: []
  - css: "face-laugh"
    code: 0xF599
    uid: 0924d17b3ef381afd1e21e23994121b7
    search: []
  - css: "face-laugh-beam"
    code: 0xF59A
    uid: 839ba83ed3e8f42e448bd760647be7f0
    search: []
  - css: "face-laugh-squint"
    code: 0xF59B
    uid: 7901842dfcc0dd83ffb6e7b64216e727
    search: []
  - css: "face-laugh-wink"
    code: 0xF59C
    uid: 0ba42a79669adfbe4eba0d509f58121f
    search: []
  - css: "face-meh-blank"
    code: 0xF5A4
    uid: d2d96fcfe60568ea53481452804a873c
    search: []
  - css: "face-rolling-eyes"
    code: 0xF5A5
    uid: 930da3a579eb0222de7c5879e4ea3d9e
    search: []
  - css: "face-sad-cry"
    code: 0xF5B3
    uid: 0b69001dd9ea5b5939f12951af541a92
    search: []
  - css: "face-sad-tear"
    code: 0xF5B4
    uid: 0cb309903ad2f6e1d36ff654d5255b2b
    search: []
  - css: "face-smile-beam"
    code: 0xF5B8
    uid: d0379b2ff3d60ef381409c6cf9cdb52a
    search: []
  - css: "star-half-stroke"
    code: 0xF5C0
    uid: 0a12078f3d95350d47465138d8cc2101
    search: []
  - css: "face-surprise"
    code: 0xF5C2
    uid: 3a717b6d19189ddac91992c41e653fd3
    search: []
  - css: "face-tired"
    code: 0xF5C8
    uid: f4a991e5462a2b3d061593dbc7297a10
    search: []
